#!/bin/bash
#
#(Scoville) habamacro/habamacro.sh
# shortcut executable shell for compiling an hmjs into a js file.
# todo: replace with gruntfile? CI config?
# Copyright 2014 Nathan Ross (nross.se@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License
( cat habamacro.sjs ; cat $1 ) | sjs -sr --output `basename $1 .mnl.js`.js
